apiVersion: v1
kind: Service
metadata:
  labels:
    app: elastic-job-k8s-controller
  name: controller-manager-metrics-service
  namespace: elastic-job
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app: elastic-job-k8s-controller
