apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-job-k8s-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: elastic-job-k8s-controller-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: elastic-job
