
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: elastic-job-k8s-controller
  name: controller-manager-metrics-monitor
  namespace: elastic-job
spec:
  endpoints:
    - path: /metrics
      port: https
  selector:
    app: elastic-job-k8s-controller
