apiVersion: v1
kind: Service
metadata:
  name: etcd-service
  namespace: elastic-job
spec:
  ports:
  - name: etcd-client-port
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: etcd
  name: etcd
  namespace: elastic-job
spec:
  containers:
  - command:
    - /usr/local/bin/etcd
    - --data-dir
    - /var/lib/etcd
    - --enable-v2
    - --listen-client-urls
    - http://0.0.0.0:2379
    - --advertise-client-urls
    - http://0.0.0.0:2379
    - --initial-cluster-state
    - new
    image: quay.io/coreos/etcd:latest
    name: etcd
    ports:
    - containerPort: 2379
      name: client
      protocol: TCP
    - containerPort: 2380
      name: server
      protocol: TCP
  restartPolicy: Always
